version: 2
updates:
  - package-ecosystem: "gomod" 
    directory: "/" 
    schedule:
      interval: "daily"
    commit-message:
      prefix: "🌱"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "🤖"
